### ISSUE TITLE
Missing 'aimos_util' module when running the train_rtx.py

### ISSUE THREAD

**Issue by ylqi** [rainbow979/robodreamer#2]
Hi,
Thank you for sharing your code.
When I run it, I encounter the following problem:
```
Traceback (most recent call last):
  File "/mnt/hdd/ricky/robodreamer/train_rtx.py", line 15, in <module>
    from aimos_util import test_aimos
ModuleNotFoundError: No module named 'aimos_util'
```
It seems that there is a missing module called 'aimos_util'. Could you please spend some time checking it for us?

**Comment by yxchng** [comment]
@ylqi have you solved the problem?

**Comment by rainbow979** [comment]
you can directly remove this.
